#!/bin/bash
# Created by Topology-Converter v4.7.1
#    Template Revision: v4.7.1

function error() {
  echo -e "\e[0;33mERROR: The Zero Touch Provisioning script failed while running the command $BASH_COMMAND at line $BASH_LINENO.\e[0m" >&2
}
trap error ERR

SSH_URL="http://192.168.200.1/authorized_keys"
#Setup SSH key authentication for Ansible
mkdir -p /home/cumulus/.ssh
wget -O /home/cumulus/.ssh/authorized_keys $SSH_URL

# unexpire cumulus user password (new for 4.2)
passwd -x 99999 cumulus
echo 'cumulus:CumulusLinux!' | chpasswd

# make user cumulus passowrdless sudo
echo "cumulus ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/10_cumulus

#enable all debian sources & netq apps3 repo
sed -i 's/#deb/deb/g' /etc/apt/sources.list
wget -O pubkey https://apps3.cumulusnetworks.com/setup/cumulus-apps-deb.pubkey
apt-key add pubkey
rm pubkey

reboot
exit 0
#CUMULUS-AUTOPROVISIONING